import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://nget.digipay.my/plans/postpaid/PBH6100266")
    page1 = context.new_page()
    page1.goto("https://nget.digipay.my/plans/postpaid/skipekyc/update/true")
    page.get_by_role("button", name="Proceed").click()
    page.get_by_text("Switch to CelcomDigi Keep").click()
    page.locator("#serviceModal").get_by_role("button", name="Proceed").click()
    page.get_by_role("radio").first.check()
    page.get_by_role("heading", name="Principal Line").click()
    page.get_by_role("heading", name="Principal Number to Port-In").click()
    page.get_by_role("textbox", name="Enter mobile number").click()
    page.get_by_role("textbox", name="Enter mobile number").click()
    page2 = context.new_page()
    page2.close()
    page.get_by_role("textbox", name="Enter mobile number").click()
    page.get_by_role("textbox", name="Enter mobile number").fill("60180701001")
    page.get_by_role("textbox", name="Enter mobile number").press("Enter")
    page.get_by_role("button", name="Request OTP").click()
    page.get_by_role("heading", name="Verification").click()
    page.get_by_role("heading", name="Verify Your Identity").click()
    page.locator("#otp1").fill("6")
    page.locator("#otp2").fill("5")
    page.locator("#otp3").fill("4")
    page.locator("#otp4").fill("4")
    page.locator("#otp5").fill("5")
    page.locator("#otp6").fill("6")
    page.get_by_text("OTP expires in 02 mins 51 secs").click()
    page.get_by_role("heading", name="Supplementary Line", exact=True).click()
    page.get_by_role("heading", name="Port-In Supplementary Line(s)").click()
    page.locator("div:nth-child(4) > .card-header").click()
    page.get_by_role("button", name="+ Add Supplementary").click()
    page.get_by_role("heading", name="Supplementary Plan").click()
    page.get_by_role("heading", name="Select New Plan").click()
    page.get_by_role("heading", name="CelcomDigi Postpaid 5G Family 50").click()
    page.get_by_role("group", name="1 /").locator("div").nth(1).click()
    page.get_by_role("heading", name="CelcomDigi Postpaid 5G Family 40").click()
    page.get_by_role("heading", name="CelcomDigi Postpaid 5G Family 50").click()
    page.get_by_role("heading", name="Supplementary Number to Port-").click()
    page.get_by_text("Enter the supplementary").click()
    page.locator(".offcanvas-backdrop").click()
    page.get_by_role("textbox", name="Enter a mobile number").click()
    page.get_by_role("textbox", name="Enter a mobile number").fill("60180701002")
    page.get_by_role("button", name="Save").click()
    page.get_by_role("heading", name="Supplementary Line", exact=True).click()
    page.get_by_role("heading", name="Add supplementary line(s)").click()
    page.get_by_role("heading", name="Supplementary Plan").click()
    page.get_by_text("0180701002").click()
    page.locator("small").filter(has_text="CelcomDigi Postpaid 5G Family").click()
    page.get_by_role("button", name="").click()
    page.get_by_role("button", name="Proceed").click()
    page.get_by_role("heading", name="Your Selection", exact=True).click()
    page.get_by_role("heading", name="Review Your Selection").click()
    page.get_by_role("heading", name="Principal details").click()
    page.get_by_text("Port-in plan").click()
    page.locator("#plan-review-cart").get_by_text("CelcomDigi Postpaid 5G 100").click()
    page.get_by_text("RM100", exact=True).click()
    page.get_by_text("Umobile").click()
    page.get_by_text("Your current telco service").click()
    page.get_by_text("Principal number").click()
    page.get_by_text("0180701001").click()
    page.get_by_text("SIM type").first.click()
    page.get_by_text("eSIM").first.click()
    page.get_by_role("heading", name="Supplementary plan details").click()
    page.get_by_text("Supplementary 1", exact=True).click()
    page.get_by_text("CelcomDigi Postpaid 5G Family 50", exact=True).click()
    page.get_by_text("RM50", exact=True).click()
    page.get_by_text("Supplementary number").click()
    page.get_by_text("0180701002").click()
    page.get_by_text("Change Number").click()
    page.get_by_text("SIM type").nth(1).click()
    page.get_by_text("eSIM").nth(1).click()
    page.get_by_role("button", name="Proceed").click()
    page.get_by_role("heading", name="Check Out Details").click()
    page.get_by_role("heading", name="Your Details").click()
    page.get_by_role("textbox", name="Full Name").click()
    page.get_by_role("textbox", name="Full Name").click()
    page.get_by_role("textbox", name="Full Name").press("ControlOrMeta+a")
    page.get_by_role("textbox", name="Full Name").fill("EVELYN ESIMMNPSTG")
    page.get_by_role("textbox", name="Contact Number").click()
    page.get_by_role("textbox", name="Contact Number").click()
    page.get_by_role("textbox", name="Contact Number").press("ControlOrMeta+a")
    page.get_by_role("textbox", name="Contact Number").fill("601139221663")
    page.get_by_role("textbox", name="Email Address").click()
    page.get_by_role("textbox", name="Email Address").click()
    page.get_by_role("textbox", name="Email Address").fill("eve")
    page1.close()
    page3 = context.new_page()
    page3.goto("http://10.89.10.38:8082/ppa/login.htm")
    page3.get_by_role("heading", name="Terms and Conditions ×").click()
    page3.get_by_text("×").click()
    page3.get_by_role("textbox", name="User ID:").click()
    page3.get_by_role("textbox", name="User ID:").click()
    page3.get_by_role("textbox", name="User ID:").fill("V18599X")
    page3.get_by_role("textbox", name="Password:").dblclick()
    page3.get_by_role("textbox", name="Password:").click()
    page3.get_by_role("textbox", name="Password:").fill("V18599X")
    page3.locator("[id=\"_target1\"]").click()
    page3.get_by_text("×").click()
    page3.get_by_role("textbox", name="Password:").click()
    page3.get_by_role("textbox", name="Password:").click()
    page3.get_by_role("textbox", name="Password:").fill("Abc1234@")
    page3.locator("[id=\"_target1\"]").click()
    page4 = context.new_page()
    page4.goto("http://10.89.10.38:8090/ppacdtool/login.htm")
    page4.get_by_role("textbox", name="User ID").click()
    page4.get_by_role("img").click()
    page4.get_by_role("textbox", name="User ID").click()
    page4.get_by_role("textbox", name="User ID").fill("V18599X")
    page4.get_by_role("textbox", name="Password").click()
    page4.get_by_role("textbox", name="Password").click()
    page4.get_by_role("textbox", name="Password").fill("Abc1234@")
    page4.get_by_role("button", name="Login").click()
    page4.get_by_role("heading", name="Welcome to PPACD Maintenance").click()
    page4.get_by_role("link", name="PPACD Maintenance Portal").click()
    page4.get_by_role("link", name="Simulator ").click()
    page4.get_by_role("link", name=" CCH").click()
    page4.get_by_text("CCH Action * :").click()
    page4.locator("#messagecode").select_option("NPR Ack")
    page4.locator("#messagecode").select_option("NPR Accept")
    page4.locator("#messagecode").select_option("NPR Reject")
    page4.locator("#messagecode").select_option("NP RFS Broadcast")
    page4.locator("#messagecode").select_option("NP Cancel")
    page4.locator("#messagecode").select_option("NP Deact Broadcast")
    page4.locator("#messagecode").select_option("Error Notification")
    page4.locator("#messagecode").select_option("NPR")
    page4.locator("#messagecode").select_option("NPR Ack")
    page4.get_by_text("Customer Type * :").click()
    page4.get_by_text("Porting Request Form ID * :").click()
    page4.get_by_role("textbox", name="Transaction ID").click()
    page4.get_by_text("Recipient Network ID * :").click()
    page4.get_by_text("Customer Name * :").click()
    page4.locator("#customername").click()
    page4.locator("#customername").fill("EVELYN KEOY")
    page4.locator("#customername").press("Enter")
    page4.get_by_text("Customer New IC Number ** :").click()
    page4.locator("#customernewic").click()
    page4.locator("#customernewic").fill("880807010001")
    page4.locator("#customernewic").press("Enter")
    page4.get_by_text("Mobile Number 1 * :").click()
    page4.get_by_role("textbox", name="Mobile No").click()
    page4.get_by_role("textbox", name="Mobile No").fill("60180701001")
    page4.get_by_role("textbox", name="Mobile No").press("Enter")
    page4.get_by_role("button", name="Add Row").click()
    page4.get_by_text("Mobile Number 2* :").click()
    page4.get_by_role("textbox", name="Mobile No").nth(1).click()
    page4.get_by_role("textbox", name="Mobile No").nth(1).fill("60180701002")
    page4.get_by_role("textbox", name="Mobile No").nth(1).press("Enter")
    page4.get_by_role("button", name="Submit").click()
    page4.get_by_text("Please enter Port Request").click()
    page4.locator("#messagecode").select_option("NPR Accept")
    page4.get_by_text("Port ID * :").click()
    page4.locator("#portid").click()
    page4.get_by_text("Customer Type * :").click()
    page4.get_by_text("Porting Request Form ID * :").click()
    page4.get_by_role("textbox", name="Transaction ID").click()
    page4.get_by_text("Recipient Network ID * :").click()
    page4.get_by_text("Donor * :").click()
    page4.locator("#donor").select_option("ALTEL")
    page4.locator("#donor").select_option("CELCOM")
    page4.locator("#donor").select_option("DIGI")
    page4.locator("#donor").select_option("MAXIS")
    page4.locator("#donor").select_option("P1")
    page4.locator("#donor").select_option("UMOBILE")
    page4.locator("#donor").select_option("YTLCOMMS")
    page4.get_by_text("Mobile Number 1 * :").click()
    page4.get_by_role("textbox", name="Mobile No").first.click()
    page4.locator("#donorregion").select_option("1")
    page4.get_by_text("Mobile Number 2* :").click()
    page4.get_by_role("textbox", name="Mobile No").nth(1).click()
    page4.get_by_text("Donor Region *:").click()
    page4.locator("#donorregion2").select_option("0")
    page4.locator("#donorregion2").select_option("1")
    page4.locator("#donorregion2").select_option("2")
    page4.locator("#donorregion2").select_option("1")
    page4.get_by_role("button", name="Submit").click()
    page4.locator("#portid").click()
    page4.locator("#portid").fill("THEENDOFPPACDMAINTE")
    page4.get_by_text("Customer Type * : MOBILE-").click()
    page3.locator("#leftFrame").content_frame.get_by_text("Development Env (88)").click()
    page3.locator("#leftFrame").content_frame.get_by_text("Internal Network : CELCOM DIGI").click()
    page3.locator("#leftFrame").content_frame.locator("#network").select_option("2")
    page3.locator("#leftFrame").content_frame.locator("#network").select_option("1")
    page3.locator("#leftFrame").content_frame.get_by_role("cell", name="Prepaid Port-in").click()
    page3.locator("#leftFrame").content_frame.get_by_role("cell", name="Prepaid Port-out").click()
    page3.locator("#leftFrame").content_frame.get_by_role("cell", name="Postpaid Port-in (MASS/CI)").click()
    page3.locator("#leftFrame").content_frame.get_by_role("strong").click()
    page3.locator("#leftFrame").content_frame.get_by_role("cell", name="Status Monitoring").get_by_role("img").click()
    page3.locator("#mainFrame").content_frame.get_by_role("cell", name="Port Created Date Range * (dd/mm/yyyy)", exact=True).click()
    page3.locator("#mainFrame").content_frame.locator("#portCreateDateFrom").click()
    page3.locator("#mainFrame").content_frame.locator("#portCreateDateFrom").click()
    page3.locator("#mainFrame").content_frame.get_by_role("link", name="Click Here to Select a Date").first.click()
    page3.locator("#mainFrame").content_frame.locator("iframe[name=\"gToday\\:normal\\:plugins\\.js\"]").content_frame.get_by_role("link", name="7", exact=True).click()
    page3.locator("#mainFrame").content_frame.get_by_role("link", name="Click Here to Select a Date").first.click()
    page3.locator("#mainFrame").content_frame.locator("iframe[name=\"gToday\\:normal\\:plugins\\.js\"]").content_frame.get_by_role("cell", name="6", exact=True).locator("div").click()
    page3.locator("#mainFrame").content_frame.get_by_role("link", name="Click Here to Select a Date").first.click()
    page3.locator("#mainFrame").content_frame.locator("iframe[name=\"gToday\\:normal\\:plugins\\.js\"]").content_frame.get_by_role("cell", name="5", exact=True).locator("div").click()
    page3.locator("#mainFrame").content_frame.locator("#portCreateDateTo").click()
    page3.locator("#mainFrame").content_frame.locator("#portCreateDateTo").fill("07/07/2025")
    page3.once("dialog", lambda dialog: dialog.dismiss())
    page3.locator("#mainFrame").content_frame.locator("#portCreateDateTo").press("Enter")
    page3.locator("#mainFrame").content_frame.locator("#portCreateDateTo").click()
    page3.locator("#mainFrame").content_frame.locator("#portCreateDateTo").fill("07/08/2025")
    page3.locator("#mainFrame").content_frame.locator("#portCreateDateTo").press("Enter")
    page3.locator("#mainFrame").content_frame.get_by_role("row", name="Submit", exact=True).get_by_role("button").click()
    page3.locator("#mainFrame").content_frame.get_by_role("link", name="Transaction ID").click()
    page3.locator("#mainFrame").content_frame.get_by_role("link", name="Port ID").click()
    page3.locator("#mainFrame").content_frame.get_by_role("link", name="Port-in Status").click()
    page3.locator("#mainFrame").content_frame.get_by_role("link", name="Customer Name").click()
    page3.locator("#mainFrame").content_frame.get_by_role("link", name="Customer ID Number").click()
    page3.locator("#mainFrame").content_frame.get_by_role("link", name="Company Name").click()
    page3.locator("#mainFrame").content_frame.get_by_role("link", name="Port Created Date").click()
    page3.locator("#mainFrame").content_frame.get_by_role("link", name="No of Mobile No").click()
    page3.locator("#mainFrame").content_frame.locator("html").click(button="right")
    page3.locator("#mainFrame").content_frame.get_by_role("button", name="Submit").click()
    page3.locator("#mainFrame").content_frame.get_by_role("cell", name="25080709091610", exact=True).click()
    page3.locator("#mainFrame").content_frame.get_by_role("cell", name="P202508070920308568", exact=True).click()
    page3.locator("#mainFrame").content_frame.get_by_role("cell", name="NPR Activated", exact=True).click()
    page3.locator("#mainFrame").content_frame.get_by_role("cell", name="ENCIK TEST TEST", exact=True).first.click()
    page3.locator("#mainFrame").content_frame.get_by_role("cell", name="901001-02-5044", exact=True).first.click()
    page3.locator("#mainFrame").content_frame.get_by_role("cell", name="07/08/2025 09:09:20", exact=True).click()
    page3.locator("#mainFrame").content_frame.get_by_role("cell", name="25080710211611", exact=True).click()
    page3.locator("#mainFrame").content_frame.get_by_role("cell", name="P202508071049489009", exact=True).click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
