import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://nget.digipay.my/plans/postpaid/PBH6100266")
    page.get_by_role("button", name="Proceed").click()
    page1 = context.new_page()
    page.goto("https://nget.digipay.my/plans/postpaid/select-number/PBH6100266")
    page.get_by_role("textbox", name="Search a mobile number (Enter").click()
    page.get_by_role("textbox", name="Search a mobile number (Enter").fill("4362")
    page.locator("#searchnumber span").click()
    page.locator("body").press("Enter")
    page.locator("#msisdn_radio_60145836349").check()
    page.get_by_text("Pay Monthly Charged from next month onwards RM100.00 Plan RM100.00 Pay Now").first.click()
    page.get_by_role("button", name="Proceed").click()
    page.get_by_role("button", name="+ Add Supplementary").click()
    page.get_by_role("heading", name="CelcomDigi Postpaid 5G Family 50").click()
    page.get_by_role("group", name="1 /").locator("div").nth(1).click()
    page.get_by_role("textbox", name="Search a mobile number (Enter").click()
    page.get_by_role("textbox", name="Search a mobile number (Enter").fill("3242")
    page.locator("#searchnumber span").click()
    page.get_by_role("textbox", name="Search a mobile number (Enter").click()
    page.get_by_role("textbox", name="Search a mobile number (Enter").press("Enter")
    page.get_by_role("textbox", name="Search a mobile number (Enter").fill("2356")
    page.get_by_role("textbox", name="Search a mobile number (Enter").press("Enter")
    page.get_by_role("textbox", name="Search a mobile number (Enter").fill("6050")
    page.get_by_role("textbox", name="Search a mobile number (Enter").press("Enter")
    expect(page.get_by_text("860 5021")).to_be_visible()
    expect(page.locator("#select-number-sec")).to_match_aria_snapshot("- radio\n- text: /\\d+ \\d+ \\d+/")
    expect(page.get_by_text("860 5021")).to_be_visible()
    page.get_by_text("860 5021").click()
    page.get_by_role("button", name="Save").click()
    page.get_by_role("heading", name="Your Selection", exact=True).click()
    page.get_by_role("heading", name="Review Your Selection").click()
    page.get_by_role("heading", name="Principal details").click()
    page.get_by_role("heading", name="Supplementary plan details").click()
    page.get_by_role("button", name="Proceed").click()
    page.goto("https://nget.digipay.my/plans/postpaid/review-cart/PBH6100266")
    page.get_by_role("button", name="Proceed").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("heading", name="Summary of transaction").click()
    page.locator("#Credit-debit-card div").first.click()
    page.locator("#Credit-debit-card div").first.click()
    page.locator("input[name=\"CCName\"]").click()
    page.get_by_role("link", name="Credit / Debit Card").click()
    page.locator("input[name=\"CCName\"]").click()
    page.locator("input[name=\"CCName\"]").fill("EVELYN MASTER")
    page.get_by_role("listitem").filter(has_text="No.").click()
    page.locator("#CCNo").click()
    page.locator("#CCNo").click()
    page.locator("#CCNo").click()
    page.locator("#CCNo").fill("5421247004825664")
    page.locator("input[name=\"CVV\"]").click()
    page.locator("input[name=\"CVV\"]").fill("123")
    page.locator("select[name=\"CCMonth\"]").select_option("12")
    page.locator("select[name=\"CCYear\"]").select_option("28")
    page.get_by_text("Card Issuing Bank").click()
    page.locator("#CCBank").select_option("Maybank")
    page.get_by_text("I authorize DIGI 3D UAT to").click()
    page.locator("#AcceptTC").uncheck()
    page.get_by_text("I authorize DIGI 3D UAT to").click()
    page.get_by_role("button", name="» Proceed").click()
    page.goto("https://maybankard3dsecurev2uat.maybank.com.my/IMS2MBBMYACS/api/3d2/creq/brw?id=MUpVN29USU11amVHQ3NKWHhrbDkxQT09")
    page2 = context.new_page()
    page2.goto("https://mbbmgatebeta.maybank.com/otp-listing")
    page2.get_by_role("textbox", name="MGate Merchant Account ID").click()
    page2.get_by_role("textbox", name="MGate Merchant Account ID").click()
    page2.get_by_role("button", name="Search").click()
    page2.get_by_text("058723", exact=True).dblclick()
    page2.locator("body").press("ControlOrMeta+c")
    page2.locator("body").press("ControlOrMeta+c")
    page2.locator("body").press("ControlOrMeta+c")
    page2.locator("body").press("ControlOrMeta+c")
    page.get_by_role("textbox").click()
    page.get_by_role("textbox").fill("058723")
    page.locator("#submitBtn").click()
    page2.close()
    page1.close()
    page.goto("https://nget.digipay.my/plans/postpaid/order-status?fulfillment_status=Pending&payment_method=CC&payment_status=Success&reference_number=NGOS250730F5537C66F4")
    with page.expect_download() as download_info:
        page.get_by_role("button", name="Download receipt now").click()
    download = download_info.value
    page3 = context.new_page()
    page3.goto("https://dkxfwptp2ybrw.cloudfront.net/login")
    expect(page3.locator("#kt_login_sso")).to_match_aria_snapshot("- button \"Sign in with SSO\":\n  - img")
    page3.get_by_role("button", name="Sign in with SSO").click()
    page3.get_by_role("textbox", name="Enter your email or phone").click()
    page3.get_by_role("textbox", name="Enter your email or phone").click()
    page3.get_by_role("textbox", name="Enter your email or phone").fill("eve.keoy@infrontconsulting.com.my")
    page3.locator("#lightbox").click()
    page3.get_by_role("button", name="Next").click()
    page3.goto("https://login.microsoftonline.com/common/login")
    page3.get_by_role("checkbox", name="Don't show this again").check()
    page3.get_by_role("button", name="Yes").click()
    page3.get_by_role("link", name=" Orders").click()
    page3.get_by_text("Advance Search", exact=True).click()
    page3.get_by_role("textbox", name="Reference Number").click()
    page.locator("div").filter(has_text="NGOS250730F5537C66F4").nth(4).dblclick()
    page.get_by_role("heading", name="NGOS250730F5537C66F4").click()
    page.get_by_role("button").nth(1).click()
    page3.get_by_role("textbox", name="Reference Number").click()
    page3.get_by_role("textbox", name="Reference Number").fill("NGOS250730F5537C66F4")
    page3.get_by_role("button", name=" Search").click()
    with page3.expect_popup() as page4_info:
        page3.get_by_role("link", name="").click()
    page4 = page4_info.value
    page4.locator("#kt_content").get_by_text("eve.keoy@infrontconsulting.").click()
    page4.get_by_text("Telco:").click()
    page4.get_by_text("Payment Status:").click()
    page4.get_by_text("Success").click()
    page4.get_by_role("heading", name="New Principal Lines Orders").click()
    page4.get_by_role("heading", name="Payment Details").click()
    page4.get_by_text("Payment Status:").click()
    page4.get_by_text("Success").click()
    page4.get_by_text("Payment Method:").click()
    page4.get_by_text("Credit/Debit Card").click()
    page4.get_by_text("Bank:").click()
    page4.get_by_text("Reference Number:").first.click()
    page4.get_by_text("Transacted At:").first.click()
    page4.get_by_text("/Jul/2025 08:37:04 AM").click()
    page4.get_by_text("Transaction ID:").click()
    page4.get_by_text("Bank MID:").click()
    page4.get_by_text("obDE8tbkbez").click()
    page4.get_by_text("Bank Code:").click()
    page4.get_by_text("Auth Code:").click()
    page4.get_by_text("CC Type:").click()
    page4.get_by_text("CC Payment Type:").click()
    page4.get_by_text("CREDIT CARD", exact=True).click()
    page4.get_by_role("heading", name="Fulfillment Details").click()
    page4.get_by_text("Fulfillment Status:").click()
    page4.get_by_text("Processing").click()
    page4.get_by_text("Reference Number:").nth(1).click()
    page4.get_by_text("NGOS250730F5537C66F4").click()
    page4.get_by_text("Telco:").click()
    page4.get_by_text("CELCOM", exact=True).click()
    page4.get_by_text("Sim Type:").click()
    page4.get_by_text("Esim", exact=True).click()
    page4.get_by_text("Name:").click()
    page4.get_by_text("EVELYN NPLSTG").click()
    page4.get_by_text("Email:").click()
    page4.locator("#kt_content").get_by_text("eve.keoy@infrontconsulting.").click()
    page4.get_by_text("Principal MSISDN:").click()
    page4.get_by_text("60145836349").click()
    page4.get_by_text("Supplementary Line(s):").click()
    page4.get_by_text("60148605021").click()
    page4.get_by_text("Amount:").click()
    page4.get_by_text("RM 150.00").click()
    page4.get_by_text("Primary offer:").click()
    page4.get_by_text("PBH6100266-CelcomDigi").click()
    page4.goto("https://dkxfwptp2ybrw.cloudfront.net/new_line/9f82aaab-83b7-4774-ad33-350f6ad84dd8")
    page4.get_by_role("link", name="View Logs").click()
    page5 = context.new_page()
    page5.goto("chrome-error://chromewebdata/")
    page5.get_by_role("button", name="Advanced").click()
    page5.locator("#final-paragraph").click()
    page5.get_by_role("link", name="Proceed to hobs.sitapi.celcom").click()
    page5.locator("#orderId").click()
    page3.get_by_role("cell", name="NGOS250730F5537C66F4").dblclick()
    page3.locator("#kt_body").press("ControlOrMeta+c")
    page5.locator("#orderId").click()
    page5.get_by_role("cell", name="Order Id", exact=True).click()
    page5.get_by_role("cell", name="O50425175").first.dblclick()
    page5.get_by_text("HOBS / Channel Order Id: Submit Order Creation Order Provisioning GATEWAY").press("ControlOrMeta+c")
    page5.locator("#orderId").click()
    page5.locator("#orderId").fill("O50425175")
    page5.get_by_role("button", name="Order Provisioning").click()
    page5.get_by_role("button", name="Order Creation").click()
    page5.get_by_role("button", name="Order Provisioning").click()
    page5.get_by_role("button", name="Order Creation").click()
    page5.get_by_role("button", name="Order Provisioning").click()
    page6 = context.new_page()
    page6.goto("https://login.microsoftonline.com/bf048976-7110-4e87-96f3-c6744908b8be/saml2?SAMLRequest=jZFNT8MwDIbv%2FIoqV5QmlJW20To0gZAmwWUD7l5jsUptUmJ3fPx60k07IdAOOcR%2BX388nt9%2B9l2yx0Ctd7W4SrVI0DXetu6tFi%2FPD7IUt4uLOUHfDWY58s6t8X1E4iQaHZlDohZjcMYDtWQc9EiGG7NZPj2aLNVmCJ594ztxtPwv7pHBAoNIlkQYOI515x2NPYYNhn3b4Mv6sRY75oGMUpYxhSb9wG1K%2FJY22DW%2BT6fXfymg2IPRysEHhk4SNmNAGY4LyB0422FQYDuFrHjyqmMFBUOr9pGG%2BsvzPUXBSohI1AQhSkgkq%2FtatFZruCqKrJC5zlHOZlWUFmUhy5st5NuqqsrKiuT1RD2bqK%2BIRlw5YnAcQzrLpS7ktX7WpZnlRhdppsvL%2BNFaxIMc5OEconDiKBbnUJurY%2BnYQ%2F2%2B%2BuIH&sso_reload=true")
    page6.get_by_role("button", name="Use another account").click()
    page6.get_by_role("textbox", name="someone@example.com").fill("V20134X@celcomdigi.com")
    page6.get_by_role("button", name="Next").click()
    page6.locator("#i0118").fill("Password@2000")
    page6.get_by_role("button", name="Sign in").click()
    page6.get_by_role("button", name="Advanced").click()
    page6.get_by_role("link", name="Proceed to dte.ac.web.stg.").click()
    page6.get_by_role("link", name="Customer Profile").click()
    page6.get_by_text("Service Number").click()
    page6.get_by_text("Service Number").nth(1).click()
    page6.get_by_role("textbox", name="* ID").click()
    page6.locator("#root").get_by_text("Service Number").click()
    page6.get_by_title("Username").click()
    page6.locator("#root").get_by_title("Username").click()
    page6.get_by_title("NRIC", exact=True).locator("div").click()
    page6.locator("#root").get_by_title("NRIC").click()
    page6.get_by_role("textbox", name="* ID").click()
    page6.get_by_role("textbox", name="* ID").fill("880730140001")
    page6.get_by_role("button", name="Search").click()
    page4.close()
    page6.get_by_role("textbox", name="* ID").click()
    page6.get_by_role("textbox", name="* ID").press("ControlOrMeta+a")
    page6.get_by_role("textbox", name="* ID").fill("601139221663")
    page6.get_by_role("textbox", name="* ID").click()
    page6.get_by_role("textbox", name="* ID").press("ArrowLeft")
    page6.get_by_role("textbox", name="* ID").press("ArrowLeft")
    page6.get_by_role("textbox", name="* ID").press("ArrowLeft")
    page6.get_by_role("textbox", name="* ID").press("ArrowLeft")
    page6.get_by_role("textbox", name="* ID").press("ArrowLeft")
    page6.get_by_role("textbox", name="* ID").press("ArrowLeft")
    page6.get_by_role("textbox", name="* ID").press("ArrowLeft")
    page6.get_by_role("textbox", name="* ID").fill("01139221663")
    page6.get_by_role("button", name="Search").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
